"""snapshot import

Revision ID: 0002_snapshot_import
Revises: 0001_workbench
Create Date: 2026-09-21 22:08:26.241197
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_snapshot_import'
down_revision: Union[str, None] = '0001_workbench'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_EVENT_TYPES = (
    'PROJECT_CREATED', 'PROJECT_STATUS_CHANGED', 'SOURCE_REGISTERED',
    'SOURCE_VERIFICATION_STARTED', 'SOURCE_VERIFIED', 'SOURCE_MISSING_DETECTED',
    'SOURCE_CHANGED_DETECTED', 'SOURCE_UNREADABLE_DETECTED', 'NODE_DISCOVERED',
    'NODE_FORMAT_DETECTED', 'NODE_QUEUED', 'NODE_PROCESSING_STARTED',
    'CONTAINER_OPENED', 'CHILD_DISCOVERED', 'CHILD_EXTRACTED',
    'RELATIONSHIP_CREATED', 'LINEAGE_UPDATED', 'NODE_PROCESSING_FINISHED',
    'NODE_PROCESSING_BLOCKED', 'NODE_PROCESSING_FAILED', 'JOB_CREATED',
    'JOB_STARTED', 'JOB_INTERRUPTED', 'JOB_FINISHED', 'ATTEMPT_QUEUED',
    'ATTEMPT_STARTED', 'ATTEMPT_FINISHED', 'ATTEMPT_FAILED',
    'ATTEMPT_INTERRUPTED', 'ATTEMPT_CANCELLED', 'ARTIFACT_REGISTERED',
    'ARTIFACT_VERIFIED', 'ARTIFACT_INTEGRITY_FAILED',
    'ARTIFACT_VERIFICATION_INTERRUPTED', 'FILE_OPEN_REQUESTED', 'FILE_OPENED',
    'FILE_OPEN_DENIED', 'FILE_OPEN_FAILED', 'RECOVERY_STARTED',
    'RECOVERY_FINISHED', 'RECOVERY_FAILED', 'JOB_CANCELLED',
    'NODE_PROCESSING_INTERRUPTED', 'ORPHAN_QUARANTINED',
    'MANIFEST_EXPORT_REQUESTED', 'MANIFEST_EXPORTED', 'MANIFEST_EXPORT_FAILED',
    'LINEAGE_INTEGRITY_FAILED', 'LINEAGE_REBUILT', 'IMPORT_REQUESTED',
    'IMPORT_STARTED', 'IMPORT_FINISHED', 'IMPORT_FAILED', 'IMPORT_INTERRUPTED',
    'IMPORT_SNAPSHOT_CAPTURE_FINISHED', 'SNAPSHOT_COPY_STARTED',
    'SNAPSHOT_VERIFICATION_STARTED', 'SNAPSHOT_READY',
    'SNAPSHOT_INTEGRITY_FAILED', 'WORKING_FILE_MATERIALIZATION_STARTED',
    'WORKING_FILE_MATERIALIZED', 'WORKING_FILE_MATERIALIZATION_FAILED',
    'WORKING_FILE_MODIFIED', 'WORKING_FILE_MISSING', 'WORKING_FILE_UNREADABLE',
    'WORKING_FILE_RESTORED_CLEAN', 'WORKSPACE_ITEM_ADDED',
    'WORKSPACE_ITEM_MOVED', 'WORKSPACE_ITEM_DELETED', 'WORKSPACE_ITEM_RESTORED',
)

_ERROR_CODES = (
    'INPUT_NOT_FOUND', 'INPUT_UNREADABLE', 'INPUT_CHANGED_DURING_COPY',
    'INPUT_OVERLAPS_PROJECT', 'DUPLICATE_INPUT', 'UNSUPPORTED_INPUT_TYPE',
    'SNAPSHOT_PUBLISH_FAILED', 'MAX_IMPORT_ENTRY_COUNT_EXCEEDED',
    'MAX_IMPORT_TOTAL_SIZE_EXCEEDED', 'SOURCE_NOT_FOUND',
    'SOURCE_FINGERPRINT_MISMATCH', 'SOURCE_OUTSIDE_BOUNDARY', 'SYMLINK_BLOCKED',
    'PATH_TRAVERSAL_BLOCKED', 'ABSOLUTE_PATH_BLOCKED', 'DEVICE_PATH_BLOCKED',
    'INVALID_FILENAME', 'PASSWORD_REQUIRED', 'CORRUPTED_CONTAINER',
    'UNSUPPORTED_FORMAT', 'UNSUPPORTED_FEATURE', 'DEPENDENCY_UNAVAILABLE',
    'DEPENDENCY_VERSION_UNSUPPORTED', 'EXTERNAL_PROCESS_TIMEOUT',
    'EXTERNAL_PROCESS_OUTPUT_EXCEEDED', 'MANIFEST_SIZE_EXCEEDED',
    'MANIFEST_EXPORT_FAILED', 'MAX_DEPTH_EXCEEDED', 'MAX_NODE_COUNT_EXCEEDED',
    'MAX_ARCHIVE_ENTRIES_EXCEEDED', 'MAX_SINGLE_FILE_SIZE_EXCEEDED',
    'MAX_TOTAL_EXPANDED_SIZE_EXCEEDED', 'MAX_COMPRESSION_RATIO_EXCEEDED',
    'ARTIFACT_MISSING', 'ARTIFACT_UNREADABLE', 'ARTIFACT_HASH_MISMATCH',
    'OPEN_FORMAT_DENIED', 'OPEN_INTEGRITY_REQUIRED', 'OPEN_HANDOFF_FAILED',
    'RECOVERY_FAILED', 'WORKSPACE_INTEGRITY_FAILED', 'HANDLER_FAILURE',
    'INTERNAL_ERROR',
)


def upgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_sources_identity_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_sources_fingerprint_set_once")
    op.execute("DROP TRIGGER IF EXISTS trg_original_artifacts_bytes_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_original_artifact_origin_set_once")
    op.execute("DROP TRIGGER IF EXISTS trg_processing_events_append_only_update")
    op.execute("DROP TRIGGER IF EXISTS trg_processing_events_append_only_delete")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_session_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('import_session_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('input_locator', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CAPTURING', 'CAPTURED', 'FAILED', 'INTERRUPTED', name='import_item_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("(status = 'FAILED' AND error_code IS NOT NULL AND error_message IS NOT NULL) OR (status <> 'FAILED')", name=op.f('ck_import_session_items_failed_item_has_error')),
    sa.CheckConstraint('length(trim(input_locator)) > 0', name=op.f('ck_import_session_items_input_locator_not_blank')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_import_session_items_ordinal_nonnegative')),
    sa.ForeignKeyConstraint(['import_session_id', 'project_id'], ['import_sessions.id', 'import_sessions.project_id'], name=op.f('fk_import_session_items_import_session_id_import_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_import_session_items_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id', 'project_id'], ['original_snapshots.id', 'original_snapshots.project_id'], name=op.f('fk_import_session_items_snapshot_id_original_snapshots'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_session_items')),
    sa.UniqueConstraint('id', 'project_id', name='uq_import_session_items_id_project'),
    sa.UniqueConstraint('import_session_id', 'ordinal', name='uq_import_session_items_session_ordinal')
    )
    with op.batch_alter_table('import_session_items', schema=None) as batch_op:
        batch_op.create_index('ix_import_session_items_session_status', ['import_session_id', 'status'], unique=False)

    op.create_table('original_snapshot_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('parent_entry_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_id', sa.String(length=36), nullable=True),
    sa.Column('source_node_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('FILE', 'FOLDER', name='original_snapshot_entry_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("(kind = 'FILE' AND artifact_id IS NOT NULL) OR (kind = 'FOLDER' AND artifact_id IS NULL)", name=op.f('ck_original_snapshot_entries_kind_matches_artifact')),
    sa.CheckConstraint('length(original_name) > 0', name=op.f('ck_original_snapshot_entries_original_name_not_empty')),
    sa.CheckConstraint('ordinal >= 0', name=op.f('ck_original_snapshot_entries_ordinal_nonnegative')),
    sa.CheckConstraint('parent_entry_id IS NULL OR parent_entry_id <> id', name=op.f('ck_original_snapshot_entries_parent_not_self')),
    sa.ForeignKeyConstraint(['artifact_id', 'project_id', 'snapshot_id'], ['original_artifacts.id', 'original_artifacts.project_id', 'original_artifacts.snapshot_id'], name=op.f('fk_original_snapshot_entries_artifact_id_original_artifacts'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_entry_id', 'project_id', 'snapshot_id'], ['original_snapshot_entries.id', 'original_snapshot_entries.project_id', 'original_snapshot_entries.snapshot_id'], name=op.f('fk_original_snapshot_entries_parent_entry_id_original_snapshot_entries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_original_snapshot_entries_project_id_projects'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['snapshot_id', 'project_id'], ['original_snapshots.id', 'original_snapshots.project_id'], name=op.f('fk_original_snapshot_entries_snapshot_id_original_snapshots'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_node_id', 'project_id'], ['nodes.id', 'nodes.project_id'], name=op.f('fk_original_snapshot_entries_source_node_id_nodes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_original_snapshot_entries')),
    sa.UniqueConstraint('id', 'project_id', 'snapshot_id', name='uq_original_snapshot_entries_identity'),
    sa.UniqueConstraint('snapshot_id', 'parent_entry_id', 'ordinal', name='uq_original_snapshot_entries_sibling_ordinal')
    )
    with op.batch_alter_table('original_snapshot_entries', schema=None) as batch_op:
        batch_op.create_index('ix_original_snapshot_entries_parent', ['project_id', 'snapshot_id', 'parent_entry_id', 'ordinal'], unique=False)
        batch_op.create_index('uq_original_snapshot_entries_one_root', ['snapshot_id'], unique=True, sqlite_where=sa.text('parent_entry_id IS NULL'))

    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('policy_snapshot', sa.JSON(), nullable=False))
        batch_op.create_unique_constraint('uq_import_sessions_project_correlation', ['project_id', 'correlation_id'])
        batch_op.create_index(
            'uq_import_sessions_one_active_project', ['project_id'], unique=True,
            sqlite_where=sa.text("status IN ('QUEUED', 'SNAPSHOTTING', 'INSPECTING')"),
        )

    with op.batch_alter_table('original_artifacts', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_original_artifacts_id_project_snapshot', ['id', 'project_id', 'snapshot_id'])

    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_constraint(op.f('ck_sources_locator_not_blank'), type_='check')
        batch_op.drop_constraint(op.f('ck_sources_observed_size_nonnegative'), type_='check')
        batch_op.drop_constraint(op.f('ck_sources_observed_sha256_length'), type_='check')
        batch_op.drop_constraint(op.f('ck_sources_source_path_flavor'), type_='check')
        batch_op.add_column(sa.Column('snapshot_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint('uq_sources_snapshot', ['snapshot_id'])
        batch_op.create_foreign_key(batch_op.f('fk_sources_snapshot_id_original_snapshots'), 'original_snapshots', ['snapshot_id', 'project_id'], ['id', 'project_id'], ondelete='RESTRICT')
        batch_op.drop_column('registered_at')
        batch_op.drop_column('observed_sha256')
        batch_op.drop_column('last_verified_at')
        batch_op.drop_column('locator')
        batch_op.drop_column('observed_size')
        batch_op.drop_column('observed_modified_at')
        batch_op.drop_column('path_flavor')

    with op.batch_alter_table('processing_events', schema=None) as batch_op:
        batch_op.alter_column(
            'event_type',
            existing_type=sa.String(length=35),
            type_=sa.Enum(
                *_EVENT_TYPES, name='processing_event_type', native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=False,
        )
        batch_op.alter_column(
            'error_code',
            existing_type=sa.String(length=37),
            type_=sa.Enum(
                *_ERROR_CODES, name='processing_event_error_code', native_enum=False,
                create_constraint=True,
            ),
            existing_nullable=True,
        )

    op.execute("""
        CREATE TRIGGER trg_sources_identity_immutable
        BEFORE UPDATE OF project_id, snapshot_id, kind, display_name, created_at
        ON sources
        WHEN OLD.project_id IS NOT NEW.project_id
          OR OLD.snapshot_id IS NOT NEW.snapshot_id
          OR OLD.kind IS NOT NEW.kind
          OR OLD.display_name IS NOT NEW.display_name
          OR OLD.created_at IS NOT NEW.created_at
        BEGIN
            SELECT RAISE(ABORT, 'source identity is immutable');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_original_artifacts_bytes_immutable
        BEFORE UPDATE OF project_id, snapshot_id, storage_key,
                         size, sha256, observed_modified_at, created_at
        ON original_artifacts
        BEGIN
            SELECT RAISE(ABORT, 'original artifact bytes and identity are immutable');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_original_artifact_origin_set_once
        BEFORE UPDATE OF source_node_id ON original_artifacts
        WHEN OLD.source_node_id IS NOT NULL
          AND OLD.source_node_id IS NOT NEW.source_node_id
        BEGIN
            SELECT RAISE(ABORT, 'original artifact source node is immutable once assigned');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_original_snapshot_entries_identity_immutable
        BEFORE UPDATE OF project_id, snapshot_id, parent_entry_id, artifact_id,
                         kind, original_name, ordinal, created_at
        ON original_snapshot_entries
        BEGIN
            SELECT RAISE(ABORT, 'original snapshot entry identity is immutable');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_original_snapshot_entry_source_set_once
        BEFORE UPDATE OF source_node_id ON original_snapshot_entries
        WHEN OLD.source_node_id IS NOT NULL
          AND OLD.source_node_id IS NOT NEW.source_node_id
        BEGIN
            SELECT RAISE(ABORT, 'snapshot entry source node is immutable once assigned');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_processing_events_append_only_update
        BEFORE UPDATE ON processing_events
        BEGIN
            SELECT RAISE(ABORT, 'processing events are append-only');
        END
    """)
    op.execute("""
        CREATE TRIGGER trg_processing_events_append_only_delete
        BEFORE DELETE ON processing_events
        BEGIN
            SELECT RAISE(ABORT, 'processing events are append-only');
        END
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    if op.get_bind().exec_driver_sql(
        "SELECT EXISTS(SELECT 1 FROM original_snapshot_entries) "
        "OR EXISTS(SELECT 1 FROM import_session_items)"
    ).scalar():
        raise RuntimeError("cannot downgrade W2 after snapshot import data exists")
    op.execute("DROP TRIGGER IF EXISTS trg_processing_events_append_only_delete")
    op.execute("DROP TRIGGER IF EXISTS trg_processing_events_append_only_update")
    op.execute("DROP TRIGGER IF EXISTS trg_original_snapshot_entry_source_set_once")
    op.execute("DROP TRIGGER IF EXISTS trg_original_snapshot_entries_identity_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_original_artifact_origin_set_once")
    op.execute("DROP TRIGGER IF EXISTS trg_original_artifacts_bytes_immutable")
    op.execute("DROP TRIGGER IF EXISTS trg_sources_identity_immutable")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path_flavor', sa.VARCHAR(length=7), nullable=False))
        batch_op.add_column(sa.Column('observed_modified_at', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('observed_size', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('locator', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('last_verified_at', sa.VARCHAR(length=32), nullable=True))
        batch_op.add_column(sa.Column('observed_sha256', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('registered_at', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_sources_snapshot_id_original_snapshots'), type_='foreignkey')
        batch_op.drop_constraint('uq_sources_snapshot', type_='unique')
        batch_op.drop_column('created_at')
        batch_op.drop_column('snapshot_id')

    with op.batch_alter_table('original_artifacts', schema=None) as batch_op:
        batch_op.drop_constraint('uq_original_artifacts_id_project_snapshot', type_='unique')

    with op.batch_alter_table('import_sessions', schema=None) as batch_op:
        batch_op.drop_index(
            'uq_import_sessions_one_active_project',
            sqlite_where=sa.text("status IN ('QUEUED', 'SNAPSHOTTING', 'INSPECTING')"),
        )
        batch_op.drop_constraint('uq_import_sessions_project_correlation', type_='unique')
        batch_op.drop_column('policy_snapshot')

    with op.batch_alter_table('original_snapshot_entries', schema=None) as batch_op:
        batch_op.drop_index('uq_original_snapshot_entries_one_root', sqlite_where=sa.text('parent_entry_id IS NULL'))
        batch_op.drop_index('ix_original_snapshot_entries_parent')

    op.drop_table('original_snapshot_entries')
    with op.batch_alter_table('import_session_items', schema=None) as batch_op:
        batch_op.drop_index('ix_import_session_items_session_status')

    op.drop_table('import_session_items')
    # ### end Alembic commands ###
