from __future__ import annotations

from enum import Enum


class StringEnum(str, Enum):
    """Python 3.10-compatible string enum."""


class ProjectStatus(StringEnum):
    CREATED = "CREATED"
    IMPORTING = "IMPORTING"
    PROCESSING = "PROCESSING"
    READY = "READY"
    READY_WITH_WARNINGS = "READY_WITH_WARNINGS"
    FAILED = "FAILED"


class ImportSessionStatus(StringEnum):
    QUEUED = "QUEUED"
    SNAPSHOTTING = "SNAPSHOTTING"
    INSPECTING = "INSPECTING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"


class ImportItemStatus(StringEnum):
    PENDING = "PENDING"
    CAPTURING = "CAPTURING"
    CAPTURED = "CAPTURED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"


class OriginalSnapshotStatus(StringEnum):
    COPYING = "COPYING"
    VERIFYING = "VERIFYING"
    READY = "READY"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    MISSING = "MISSING"
    MISMATCH = "MISMATCH"
    UNREADABLE = "UNREADABLE"
    PURGED = "PURGED"


class OriginalSnapshotEntryKind(StringEnum):
    FILE = "FILE"
    FOLDER = "FOLDER"


class WorkspaceItemKind(StringEnum):
    FOLDER = "FOLDER"
    FILE = "FILE"
    CONTAINER_VIEW = "CONTAINER_VIEW"


class WorkspaceItemLifecycleStatus(StringEnum):
    ACTIVE = "ACTIVE"
    DELETED = "DELETED"
    PURGED = "PURGED"


class WorkspaceMaterializationStatus(StringEnum):
    VIRTUAL = "VIRTUAL"
    MATERIALIZING = "MATERIALIZING"
    MATERIALIZED = "MATERIALIZED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"


class WorkingContentStatus(StringEnum):
    CLEAN = "CLEAN"
    CHECKING = "CHECKING"
    MODIFIED = "MODIFIED"
    MISSING = "MISSING"
    UNREADABLE = "UNREADABLE"


class WorkingRefreshReason(StringEnum):
    EXPLICIT = "EXPLICIT"
    BEFORE_OPEN = "BEFORE_OPEN"
    FOCUS_GAINED = "FOCUS_GAINED"


class WorkingRevisionRole(StringEnum):
    CURRENT_CHECKPOINT = "CURRENT_CHECKPOINT"
    PREVIOUS = "PREVIOUS"


class RecoveryRunStatus(StringEnum):
    DETECTED = "DETECTED"
    AWAITING_CONFIRMATION = "AWAITING_CONFIRMATION"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"


class RecoveryItemStatus(StringEnum):
    DISCOVERED = "DISCOVERED"
    PLANNED = "PLANNED"
    RESTORED = "RESTORED"
    QUARANTINED = "QUARANTINED"
    REMOVED_REPRODUCIBLE = "REMOVED_REPRODUCIBLE"
    UNCHANGED = "UNCHANGED"
    FAILED = "FAILED"


class RecoveryItemKind(StringEnum):
    SNAPSHOT_STAGING = "SNAPSHOT_STAGING"
    MATERIALIZATION_STAGING = "MATERIALIZATION_STAGING"
    VERSION_STAGING = "VERSION_STAGING"
    IMPORT_UNDO_STAGING = "IMPORT_UNDO_STAGING"
    INSPECTION_CACHE = "INSPECTION_CACHE"
    UNREGISTERED_ORIGINAL = "UNREGISTERED_ORIGINAL"
    UNREGISTERED_WORKING = "UNREGISTERED_WORKING"
    UNREGISTERED_VERSION = "UNREGISTERED_VERSION"
    UNKNOWN_STAGING = "UNKNOWN_STAGING"
    OPERATION_MANIFEST = "OPERATION_MANIFEST"


class RecoveryAction(StringEnum):
    RESTORE = "RESTORE"
    QUARANTINE = "QUARANTINE"
    REMOVE_REPRODUCIBLE = "REMOVE_REPRODUCIBLE"
    REMOVE_MANIFEST = "REMOVE_MANIFEST"
    UNCHANGED = "UNCHANGED"


class SourceKind(StringEnum):
    FILE = "FILE"
    FOLDER = "FOLDER"


class PathFlavor(StringEnum):
    WINDOWS = "WINDOWS"
    POSIX = "POSIX"
    URI = "URI"


class SourceStatus(StringEnum):
    REGISTERED = "REGISTERED"
    VERIFYING = "VERIFYING"
    AVAILABLE = "AVAILABLE"
    MISSING = "MISSING"
    CHANGED = "CHANGED"
    UNREADABLE = "UNREADABLE"
    PURGED = "PURGED"


class NodeKind(StringEnum):
    CONTAINER = "CONTAINER"
    FILE = "FILE"


class NodeFormat(StringEnum):
    FOLDER = "FOLDER"
    ZIP = "ZIP"
    RAR = "RAR"
    SEVEN_Z = "SEVEN_Z"
    MSG = "MSG"
    EML = "EML"
    XLSX = "XLSX"
    XLS = "XLS"
    CSV = "CSV"
    PDF = "PDF"
    DOCX = "DOCX"
    DOC = "DOC"
    PPTX = "PPTX"
    PPT = "PPT"
    TXT = "TXT"
    JPG = "JPG"
    JPEG = "JPEG"
    PNG = "PNG"
    UNKNOWN = "UNKNOWN"


class NodeProcessingStatus(StringEnum):
    DISCOVERED = "DISCOVERED"
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    INTERRUPTED = "INTERRUPTED"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    UNSUPPORTED = "UNSUPPORTED"
    PASSWORD_REQUIRED = "PASSWORD_REQUIRED"
    CORRUPTED = "CORRUPTED"
    LIMIT_EXCEEDED = "LIMIT_EXCEEDED"
    SECURITY_BLOCKED = "SECURITY_BLOCKED"
    SOURCE_MISSING = "SOURCE_MISSING"
    SOURCE_CHANGED = "SOURCE_CHANGED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ArtifactRole(StringEnum):
    ORIGINAL_REFERENCE = "ORIGINAL_REFERENCE"
    EXTRACTED_ARTIFACT = "EXTRACTED_ARTIFACT"
    WORKSPACE_COPY = "WORKSPACE_COPY"


class ArtifactScope(StringEnum):
    EXTERNAL_SOURCE = "EXTERNAL_SOURCE"
    PROJECT_WORKSPACE = "PROJECT_WORKSPACE"


class ArtifactIntegrityStatus(StringEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    MISSING = "MISSING"
    MISMATCH = "MISMATCH"
    UNREADABLE = "UNREADABLE"
    PURGED = "PURGED"


class WorkspaceExportKind(StringEnum):
    FILE = "FILE"
    DIRECTORY = "DIRECTORY"
    ZIP = "ZIP"


class RelationshipType(StringEnum):
    FOLDER_CONTAINS = "FOLDER_CONTAINS"
    ARCHIVE_ENTRY = "ARCHIVE_ENTRY"
    EMAIL_ATTACHMENT = "EMAIL_ATTACHMENT"
    EMBEDDED_MESSAGE = "EMBEDDED_MESSAGE"


class MaterializationLocatorKind(StringEnum):
    SNAPSHOT_ENTRY = "SNAPSHOT_ENTRY"
    ZIP_MEMBER = "ZIP_MEMBER"
    EML_PART = "EML_PART"
    MSG_ATTACHMENT = "MSG_ATTACHMENT"
    SEVEN_Z_MEMBER = "SEVEN_Z_MEMBER"
    RAR_MEMBER = "RAR_MEMBER"


class MetadataValueType(StringEnum):
    TEXT = "TEXT"
    INTEGER = "INTEGER"
    REAL = "REAL"
    BOOLEAN = "BOOLEAN"
    DATETIME = "DATETIME"
    JSON = "JSON"


class JobType(StringEnum):
    IMPORT_SOURCE = "IMPORT_SOURCE"
    PROCESS_PROJECT = "PROCESS_PROJECT"
    RETRY_NODE = "RETRY_NODE"
    RECOVER_INTERRUPTED = "RECOVER_INTERRUPTED"


class JobStatus(StringEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    PARTIAL_SUCCESS = "PARTIAL_SUCCESS"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    CANCELLED = "CANCELLED"


class AttemptStatus(StringEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    INTERRUPTED = "INTERRUPTED"
    CANCELLED = "CANCELLED"


class ProcessingStage(StringEnum):
    REGISTER_SOURCE = "REGISTER_SOURCE"
    VERIFY_SOURCE = "VERIFY_SOURCE"
    DISCOVER_NODE = "DISCOVER_NODE"
    DETECT_FORMAT = "DETECT_FORMAT"
    INSPECT_CONTAINER = "INSPECT_CONTAINER"
    EXTRACT_CHILD = "EXTRACT_CHILD"
    REGISTER_CHILD = "REGISTER_CHILD"
    PERSIST_RELATIONSHIP = "PERSIST_RELATIONSHIP"
    UPDATE_LINEAGE = "UPDATE_LINEAGE"
    VERIFY_ARTIFACT = "VERIFY_ARTIFACT"
    OPEN_FILE = "OPEN_FILE"
    EXPORT_MANIFEST = "EXPORT_MANIFEST"


class EventSeverity(StringEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"


class EventType(StringEnum):
    PROJECT_CREATED = "PROJECT_CREATED"
    PROJECT_STATUS_CHANGED = "PROJECT_STATUS_CHANGED"
    SOURCE_REGISTERED = "SOURCE_REGISTERED"
    SOURCE_VERIFICATION_STARTED = "SOURCE_VERIFICATION_STARTED"
    SOURCE_VERIFIED = "SOURCE_VERIFIED"
    SOURCE_MISSING_DETECTED = "SOURCE_MISSING_DETECTED"
    SOURCE_CHANGED_DETECTED = "SOURCE_CHANGED_DETECTED"
    SOURCE_UNREADABLE_DETECTED = "SOURCE_UNREADABLE_DETECTED"
    NODE_DISCOVERED = "NODE_DISCOVERED"
    NODE_FORMAT_DETECTED = "NODE_FORMAT_DETECTED"
    NODE_QUEUED = "NODE_QUEUED"
    NODE_PROCESSING_STARTED = "NODE_PROCESSING_STARTED"
    CONTAINER_OPENED = "CONTAINER_OPENED"
    CHILD_DISCOVERED = "CHILD_DISCOVERED"
    CHILD_EXTRACTED = "CHILD_EXTRACTED"
    RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED"
    LINEAGE_UPDATED = "LINEAGE_UPDATED"
    NODE_PROCESSING_FINISHED = "NODE_PROCESSING_FINISHED"
    NODE_PROCESSING_BLOCKED = "NODE_PROCESSING_BLOCKED"
    NODE_PROCESSING_FAILED = "NODE_PROCESSING_FAILED"
    JOB_CREATED = "JOB_CREATED"
    JOB_STARTED = "JOB_STARTED"
    JOB_INTERRUPTED = "JOB_INTERRUPTED"
    JOB_FINISHED = "JOB_FINISHED"
    ATTEMPT_QUEUED = "ATTEMPT_QUEUED"
    ATTEMPT_STARTED = "ATTEMPT_STARTED"
    ATTEMPT_FINISHED = "ATTEMPT_FINISHED"
    ATTEMPT_FAILED = "ATTEMPT_FAILED"
    ATTEMPT_INTERRUPTED = "ATTEMPT_INTERRUPTED"
    ATTEMPT_CANCELLED = "ATTEMPT_CANCELLED"
    ARTIFACT_REGISTERED = "ARTIFACT_REGISTERED"
    ARTIFACT_VERIFIED = "ARTIFACT_VERIFIED"
    ARTIFACT_INTEGRITY_FAILED = "ARTIFACT_INTEGRITY_FAILED"
    ARTIFACT_VERIFICATION_INTERRUPTED = "ARTIFACT_VERIFICATION_INTERRUPTED"
    FILE_OPEN_REQUESTED = "FILE_OPEN_REQUESTED"
    FILE_OPENED = "FILE_OPENED"
    FILE_OPEN_DENIED = "FILE_OPEN_DENIED"
    FILE_OPEN_FAILED = "FILE_OPEN_FAILED"
    RECOVERY_STARTED = "RECOVERY_STARTED"
    RECOVERY_FINISHED = "RECOVERY_FINISHED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    JOB_CANCELLED = "JOB_CANCELLED"
    NODE_PROCESSING_INTERRUPTED = "NODE_PROCESSING_INTERRUPTED"
    ORPHAN_QUARANTINED = "ORPHAN_QUARANTINED"
    MANIFEST_EXPORT_REQUESTED = "MANIFEST_EXPORT_REQUESTED"
    MANIFEST_EXPORTED = "MANIFEST_EXPORTED"
    MANIFEST_EXPORT_FAILED = "MANIFEST_EXPORT_FAILED"
    LINEAGE_INTEGRITY_FAILED = "LINEAGE_INTEGRITY_FAILED"
    LINEAGE_REBUILT = "LINEAGE_REBUILT"
    IMPORT_REQUESTED = "IMPORT_REQUESTED"
    IMPORT_STARTED = "IMPORT_STARTED"
    IMPORT_FINISHED = "IMPORT_FINISHED"
    IMPORT_FAILED = "IMPORT_FAILED"
    IMPORT_INTERRUPTED = "IMPORT_INTERRUPTED"
    IMPORT_SNAPSHOT_CAPTURE_FINISHED = "IMPORT_SNAPSHOT_CAPTURE_FINISHED"
    SNAPSHOT_COPY_STARTED = "SNAPSHOT_COPY_STARTED"
    SNAPSHOT_VERIFICATION_STARTED = "SNAPSHOT_VERIFICATION_STARTED"
    SNAPSHOT_READY = "SNAPSHOT_READY"
    SNAPSHOT_INTEGRITY_FAILED = "SNAPSHOT_INTEGRITY_FAILED"
    WORKING_FILE_MATERIALIZATION_STARTED = (
        "WORKING_FILE_MATERIALIZATION_STARTED"
    )
    WORKING_FILE_MATERIALIZED = "WORKING_FILE_MATERIALIZED"
    WORKING_FILE_MATERIALIZATION_FAILED = (
        "WORKING_FILE_MATERIALIZATION_FAILED"
    )
    WORKING_FILE_MODIFIED = "WORKING_FILE_MODIFIED"
    WORKING_FILE_MISSING = "WORKING_FILE_MISSING"
    WORKING_FILE_UNREADABLE = "WORKING_FILE_UNREADABLE"
    WORKING_FILE_RESTORED_CLEAN = "WORKING_FILE_RESTORED_CLEAN"
    WORKING_VERSION_CAPTURED = "WORKING_VERSION_CAPTURED"
    WORKING_FILE_ROLLED_BACK = "WORKING_FILE_ROLLED_BACK"
    WORKSPACE_EXPORT_REQUESTED = "WORKSPACE_EXPORT_REQUESTED"
    WORKSPACE_EXPORT_COMPLETED = "WORKSPACE_EXPORT_COMPLETED"
    WORKSPACE_EXPORT_FAILED = "WORKSPACE_EXPORT_FAILED"
    IMPORT_ITEM_UNDO_REQUESTED = "IMPORT_ITEM_UNDO_REQUESTED"
    IMPORT_ITEM_UNDO_COMPLETED = "IMPORT_ITEM_UNDO_COMPLETED"
    IMPORT_ITEM_UNDO_FAILED = "IMPORT_ITEM_UNDO_FAILED"
    WORKSPACE_ITEM_ADDED = "WORKSPACE_ITEM_ADDED"
    WORKSPACE_ITEM_MOVED = "WORKSPACE_ITEM_MOVED"
    WORKSPACE_ITEM_DELETED = "WORKSPACE_ITEM_DELETED"
    WORKSPACE_ITEM_RESTORED = "WORKSPACE_ITEM_RESTORED"


class ErrorCategory(StringEnum):
    SOURCE = "SOURCE"
    FORMAT = "FORMAT"
    SECURITY = "SECURITY"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    INTEGRITY = "INTEGRITY"
    PROCESSING = "PROCESSING"
    INTERNAL = "INTERNAL"


class ErrorCode(StringEnum):
    INPUT_NOT_FOUND = "INPUT_NOT_FOUND"
    INPUT_UNREADABLE = "INPUT_UNREADABLE"
    INPUT_CHANGED_DURING_COPY = "INPUT_CHANGED_DURING_COPY"
    INPUT_OVERLAPS_PROJECT = "INPUT_OVERLAPS_PROJECT"
    DUPLICATE_INPUT = "DUPLICATE_INPUT"
    UNSUPPORTED_INPUT_TYPE = "UNSUPPORTED_INPUT_TYPE"
    SNAPSHOT_PUBLISH_FAILED = "SNAPSHOT_PUBLISH_FAILED"
    MAX_IMPORT_ENTRY_COUNT_EXCEEDED = "MAX_IMPORT_ENTRY_COUNT_EXCEEDED"
    MAX_IMPORT_TOTAL_SIZE_EXCEEDED = "MAX_IMPORT_TOTAL_SIZE_EXCEEDED"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    SOURCE_FINGERPRINT_MISMATCH = "SOURCE_FINGERPRINT_MISMATCH"
    SOURCE_OUTSIDE_BOUNDARY = "SOURCE_OUTSIDE_BOUNDARY"
    SYMLINK_BLOCKED = "SYMLINK_BLOCKED"
    PATH_TRAVERSAL_BLOCKED = "PATH_TRAVERSAL_BLOCKED"
    ABSOLUTE_PATH_BLOCKED = "ABSOLUTE_PATH_BLOCKED"
    DEVICE_PATH_BLOCKED = "DEVICE_PATH_BLOCKED"
    INVALID_FILENAME = "INVALID_FILENAME"
    PASSWORD_REQUIRED = "PASSWORD_REQUIRED"
    CORRUPTED_CONTAINER = "CORRUPTED_CONTAINER"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    UNSUPPORTED_FEATURE = "UNSUPPORTED_FEATURE"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"
    DEPENDENCY_VERSION_UNSUPPORTED = "DEPENDENCY_VERSION_UNSUPPORTED"
    EXTERNAL_PROCESS_TIMEOUT = "EXTERNAL_PROCESS_TIMEOUT"
    EXTERNAL_PROCESS_OUTPUT_EXCEEDED = "EXTERNAL_PROCESS_OUTPUT_EXCEEDED"
    MANIFEST_SIZE_EXCEEDED = "MANIFEST_SIZE_EXCEEDED"
    MANIFEST_EXPORT_FAILED = "MANIFEST_EXPORT_FAILED"
    MAX_DEPTH_EXCEEDED = "MAX_DEPTH_EXCEEDED"
    MAX_NODE_COUNT_EXCEEDED = "MAX_NODE_COUNT_EXCEEDED"
    MAX_ARCHIVE_ENTRIES_EXCEEDED = "MAX_ARCHIVE_ENTRIES_EXCEEDED"
    MAX_SINGLE_FILE_SIZE_EXCEEDED = "MAX_SINGLE_FILE_SIZE_EXCEEDED"
    MAX_TOTAL_EXPANDED_SIZE_EXCEEDED = "MAX_TOTAL_EXPANDED_SIZE_EXCEEDED"
    MAX_COMPRESSION_RATIO_EXCEEDED = "MAX_COMPRESSION_RATIO_EXCEEDED"
    ARTIFACT_MISSING = "ARTIFACT_MISSING"
    ARTIFACT_UNREADABLE = "ARTIFACT_UNREADABLE"
    ARTIFACT_HASH_MISMATCH = "ARTIFACT_HASH_MISMATCH"
    OPEN_FORMAT_DENIED = "OPEN_FORMAT_DENIED"
    OPEN_INTEGRITY_REQUIRED = "OPEN_INTEGRITY_REQUIRED"
    OPEN_HANDOFF_FAILED = "OPEN_HANDOFF_FAILED"
    RECOVERY_FAILED = "RECOVERY_FAILED"
    WORKSPACE_INTEGRITY_FAILED = "WORKSPACE_INTEGRITY_FAILED"
    WORKING_VERSION_NOT_FOUND = "WORKING_VERSION_NOT_FOUND"
    WORKING_VERSION_INTEGRITY_FAILED = "WORKING_VERSION_INTEGRITY_FAILED"
    EXPORT_DESTINATION_INVALID = "EXPORT_DESTINATION_INVALID"
    EXPORT_PATH_COLLISION = "EXPORT_PATH_COLLISION"
    EXPORT_FAILED = "EXPORT_FAILED"
    IMPORT_ITEM_NOT_UNDOABLE = "IMPORT_ITEM_NOT_UNDOABLE"
    IMPORT_ITEM_UNDO_FAILED = "IMPORT_ITEM_UNDO_FAILED"
    HANDLER_FAILURE = "HANDLER_FAILURE"
    INTERNAL_ERROR = "INTERNAL_ERROR"
